name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.event.pull_request.merged }}
  if_merged:
    if: github.event.pull_request.merged == true
    steps:
      - name: Fail the Build
        uses: cutenode/action-always-fail@v1.0.0
