name: Run during push
on:
  push:
    branches:
      - "develop"
      - "feature/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.ref }}
      - name: Fail the Build
        id: alwaysFailed
        if: contains(github.ref_name, 'feature')
        uses: cutenode/action-always-fail@v1.0.0
      - name: Run archive
        if: success() || (failure() && steps.alwaysFailed.conclusion == 'failure')
        run: echo Run archive
