name: CI
on:
  pull_request:
    branches:
      - "develop"
      - "feature/**"
jobs:
  build:
    name: run_before_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Fail the Build
        if: github.ref == 'refs/heads/feature'
        uses: cutenode/action-always-fail@v1.0.0

