name: CI
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: run_before_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!